## 1. Write a Python program to create two matrices and perform addition, subtraction, multiplication and division operation on matrix 

In [2]:
import numpy as np

x = np.array([[3, 2], [4, 10]])
y = np.array([[2, 7], [5, 10]])
print ("Addition of two matrices: ")
print (np.add(x,y))
print ("Subtraction of two matrices : ")
print (np.subtract(x,y))
print ("Matrix Division :")
print (np.divide(x,y))
print ("Multiplication of two matrices: ")
print (np.multiply(x,y))

Addition of two matrices: 
[[ 5  9]
 [ 9 20]]
Subtraction of two matrices : 
[[ 1 -5]
 [-1  0]]
Matrix Division :
[[1.5        0.28571429]
 [0.8        1.        ]]
Multiplication of two matrices: 
[[  6  14]
 [ 20 100]]


## 2.Write a Python program to concatenate two strings.


In [3]:
str1 = "Amol "  
str2 = "Kulkarni"  
str3 = str1 + str2  
print("Concatenate string: ",str3) 

Concatenate string:  Amol Kulkarni


## 3.Write a NumPy program to generate six random integers between 10 and 30

In [4]:
import numpy as np
x = np.random.randint(low=10, high=30, size=6)
print(x)

[11 17 16 15 17 18]
